const themes = [
  "Briefly tell about a movie you saw recently.",
  "Can television (or videogames) influence your behaviour? How?",
  "Describe a famous park or recreation area in your home country.",
  "Describe a memorable birthday celebration.",
  "Describe a place you go for recreation or exercise.",
  "Describe a place you will never forget.",
  "Describe a sporting event you attended recently.",
  "Describe a time when you felt vengeful.",
  "Describe an interesting neighbor you have had.",
  "Describe someone you respect deeply.",
  "Describe something you could never give away.",
  "Describe the nightlife in a city you are familiar with.",
  "Describe your childhood home.",
  "Do you think it is necessary to have alcohol at a party in order to have a good time?",
  "Do you think there is too much fighting on t.v. Why or why not?",
  "Does it bother you to be around someone who has bad manners?",
  "Explain how to play your favorite game.",
  "Explain why we say, “dead as a door nail”.",
  "Families are important because…",
  "How do feel on (any holiday)?",
  "How do you feel about your appearance?",
  "How do you feel during a thunderstorm?",
  "How do you feel on a warm sunny day?",
  "How do you feel on Thanksgiving? What are you thankful for?",
  "How do you feel on the first day of school?",
  "How do you feel on the first day of winter? Why?",
  "How do you feel when it’s your birthday? Why?",
  "How do you feel when something scares you? What do you do when this happens?",
  "How do you feel when you are in bed with the lights out?",
  "How do you feel when you do something that is very good?",
  "How do you feel when you do something wrong?",
  "How do you feel when you have had a fight with your best friend?",
  "How do you feel when you play a trick on someone?",
  "How do you feel when you sleep at someone’s house?",
  "How do you feel when you stay with a babysitter?",
  "How do you feel when you want something very badly and you cannot have it? Why is this so important to have?",
  "How do you feel when your parents are upset with you? Why do they become upset with you?",
  "How do you feel when you’re leaving home on vacation?",
  "How do you have the most fun–alone, with a large group, with a few friends–and why?",
  "How do you think eating junk food affects you?",
  "How do you think the new child would feel?",
  "How do you think your friend felt?",
  "How would you change the world to make it better?",
  "How would you describe your house to someone who has never visited there before?",
  "How would you feel if a new child moved into your neighbourhood?",
  "How would you feel if someone told you that you were his or her best friend?",
  "How would you feel if you were going to be on a show? Why?",
  "If it were your job to decide what shows can be on t.v., how would you choose?",
  "If there were no rules, what do you think would happen?",
  "If you could break the Guiness Book of Records it would be for?",
  "If you could change one major historical event, what would it be?",
  "If you could change one thing about your past, what would it be?",
  "If you could do whatever you wanted to right now, what would you do?",
  "If you could give any gift in the world, what would you give and to whom?",
  "If you could have been someone in history, who would you have been?",
  "If you could live anywhere in the world, where would it be?",
  "If you could only take 3 people with you on a trip around the world, who would you take and why?",
  "If you could participate in an Olympic event, which one would you choose and why?",
  "If you had to describe yourself as a colour, which would you choose?",
  "If you owned a store, what would you do to discourage people from stealing from you?",
  "If you received any sum of money as a gift, what would you do with it?",
  "If you were a mouse in your house in the evening, what would you see your family doing?",
  "If you were five years older you would…",
  "If you were lost in the woods and it got dark, what would you do?",
  "If you were principal of this school, what would you do?",
  "If your friend told you of a secret plan to run away from home, what would you do and why?",
  "Once, when you were embarrassed, what happened?",
  "Once, when you were very frightened, what happened?",
  "Once, when your feelings were hurt, what happened?",
  "Should animals be used for medical research?",
  "Should cellphones be allowed in school?",
  "Should junk food be banned from schools?",
  "Should people be prohibited from smoking in certain places?",
  "Should schools be year-round?",
  "Should skateboards be allowed on sidewalks?",
  "Should students be required to learn a second language?",
  "Should the Canadian Government financially support Olympic teams?",
  "Should there be a dress code in places such as school, restaurants, and places of business? Why or why not?",
  "Should you be required to wear a bike helmet? Why or why not?",
  "Should you have to do chores around the house? Why or why not?",
  "Should you have to take tests in school?",
  "Tell about a “close call” you had recently.",
  "Tell about a recent job interview.",
  "Tell about a time when you inadvertently caused trouble for someone else.",
  "Tell about a time when you lied to your parents, boss, or teacher.",
  "Tell about a time when you lost something.",
  "Tell about a time when you were treated unfairly.",
  "Tell about one of your fondest childhood memories.",
  "Tell about something you made ?from scratch.?",
  "Tell about something you wish had never happened.",
  "Tell how to discipline an unruly child.",
  "Tell how to dump a boyfriend/girlfriend.",
  "Tell how to feed family members who drop by unexpectedly.",
  "Tell how to find something on the Internet.",
  "Tell how to get a discount on an expensive item.",
  "Tell how to get a good table at a restaurant.",
  "Tell how to get from your house to the supermarket.",
  "Tell how to get someone to fall in love with you.",
  "Tell how to make a paper airplane.",
  "Tell what to do in an earthquake.",
  "Think of the best teacher you ever had. Why were they a good teacher?",
  "Think of your favourite toy. Why do you like it best?",
  "What advice would you give a new student?",
  "What advice would you give to someone who stole something but now feels guilty?",
  "What are junk foods?",
  "What are some examples of prejudice?",
  "What are some nutritious foods that you like?",
  "What are some rules you have to follow at home?",
  "What are you afraid of? Why?",
  "What colour makes you think of happiness?",
  "What do we mean when we say, “Hitch your wagon to a star”?",
  "What do we mean when we say, “The grass is always greener on the other side of the fence”?",
  "What do we mean when we say, “You can catch more flies with honey than with vinegar”?",
  "What do you do for exercise?",
  "What do you like most about yourself?",
  "What do you like to do in your free time?",
  "What do you think about ghosts?",
  "What do you think about having set rules for people to follow?",
  "What do you think about people polluting the environment?",
  "What do you think about people who are inconsiderate of others?",
  "What do you think about people who take advantage of others?",
  "What do you think about students having to wear school uniforms?",
  "What do you think about the amount of violence on T.V.?",
  "What do you think about when you can’t fall asleep?",
  "What do you think courage means?",
  "What do you think makes a good friend?",
  "What do you think makes a happy family?",
  "What do you think of 3D movies?",
  "What do you think of someone who has bad manners?",
  "What do you think should be done to keep people who are under the influence of alcohol off the road?",
  "What do you think someone your age can do to help reduce the amount of pollution in our environment?",
  "What do you think the world needs now?",
  "What do you think the world will be like when you are a grown up?",
  "What do you think your friends say to each other when you’re not around?",
  "What does “Clothes make the person” mean to you?",
  "What does “Have your cake and eat it too” mean to you?",
  "What does “still waters run deep” mean to you?",
  "What does “The early bird gets the worm” mean to you?",
  "What does “There are two sides to every coin” mean to you?",
  "What does “You can’t take it with you” mean?",
  "What does Canada mean to you?",
  "What eccentric behaviour in a friend disturbs you the most?",
  "What effects do cigarette and alcohol advertising have on young people?",
  "What effects does watching violence have on people?",
  "What four things are most important in your life?",
  "What has been the most fun activity at school so far?",
  "What if all the streets were rivers? What would be different?",
  "What if cows gave root beer instead of milk?",
  "What if everyone lived under water? Where would people live? What games would children play? What would school be like?",
  "What if you could walk up walls and across ceilings?",
  "What is a good neighbour?",
  "What is more important to you, appearance or personality?",
  "What is most important to you in a friend–loyalty, generosity, honesty–why?",
  "What is something that makes you feel sad?",
  "What is something that makes you melancholy?",
  "What is something that really bugs you?",
  "What is something that really makes you angry?",
  "What is something you are optimistic about?",
  "What is something you are pessimistic about?",
  "What is something you dislike about yourself?",
  "What is something you do well?",
  "What is the best advice you ever received?",
  "What is the best birthday present you could receive?",
  "What is the best birthday present you ever received?",
  "What is the best way to treat meddlesome people?",
  "What is the funniest dinner you’ve ever had with your family?",
  "What is the meaning of “He laughs best who laughs last”?",
  "What is the most ludicrous outfit you can think of?",
  "What is the worst thing parents can do to their children?",
  "What is your favourite book and why?",
  "What is your favourite day of the week?",
  "What is your favourite holiday? What makes this holiday special?",
  "What is your favourite month? Why?",
  "What is your favourite room in your home and why?",
  "What is your favourite song and why?",
  "What is your favourite time of day?",
  "What is your idea of a dull evening?",
  "What is your most indispensable possession and why?",
  "What is your opinion about a current politician?",
  "What is your opinion about cellular phones?",
  "What is your opinion about cloning?",
  "What is your opinion about fortune telling?",
  "What is your opinion about legalizing marijuana?",
  "What is your opinion about recycling?",
  "What is your opinion about the tabloids?",
  "What is your opinion about the welfare system?",
  "What is your opinion about violence on television?",
  "What is your opinion about women in the military?",
  "What kind of animal would you like to be and why?",
  "What kind of pet would you most like to have–monkey, snake, goat–why?",
  "What kind of program do you enjoy most on TV–detective shows, comedies, game shows–and why?",
  "What kind of t.v. commercial would you like to make? Describe it.",
  "What kind of trophy would you like to win?",
  "What makes you feel safe?",
  "What makes you laugh?",
  "What makes your best friend your best friend?",
  "What parts of nature do you like best?",
  "What pollutants do you think do the most damage and why?",
  "What quality do you like about yourself–creativity, personality, appearance–why?",
  "What talents do you have?",
  "What things are better than going to school? Why?",
  "What things do you think are beautiful?",
  "What three words would describe you right now?",
  "What TV or movie star would you like to invite to your birthday party?",
  "What would happen if animals could talk? What are some of the questions you would like to ask animals?",
  "What would happen if children ruled the world?",
  "What would happen if everyone lived in space? What type of houses would they live in? What type of clothing would they wear? What type of food would they eat? How would they travel?",
  "What would happen if everyone wore the same clothes?",
  "What would happen if it really did rain cats and dogs?",
  "What would happen if people never co-operated? Why do you think it is important to co-operate?",
  "What would happen if there were no cars, buses, trains, boats, or planes? How would this change your life?",
  "What would happen if there were no television? Why would this be good? bad?",
  "What would happen if you could become invisible whenever you wanted to? What are some of the things you could do that you cannot do now?",
  "What would happen if you could fly whenever you wanted? When would you use this ability?",
  "What would happen if you found gold in your backyard?",
  "What would happen if you grew taller than trees? How would this change your life?",
  "What would happen if you loved your neighbour as yourself? What if everyone did?",
  "What would happen if you threw a piece of trash on the ground? What if everyone did?",
  "What would you do if a bully bothered you on your way home?",
  "What would you do if a friend borrows things from you but never returns them?",
  "What would you do if a friend comes to your house and his/her mom doesn’t know he’s/she’s there?",
  "What would you do if an hour before the party you remember you don’t have a gift?",
  "What would you do if only one hot dog is left and neither you nor your friend have had one?",
  "What would you do if someone accused you of a crime you didn’t commit?",
  "What would you do if someone got in front of you when you were in line at the movies?",
  "What would you do if someone said you did something wrong and you didn’t?",
  "What would you do if someone told you a joke that you don’t think is funny?",
  "What would you do if the surprise party was for you but you weren’t surprised?",
  "What would you do if two of your best friends went to the movies without inviting you?",
  "What would you do if you did very poorly of a test?",
  "What would you do if you didn’t have enough money to pay your bills?",
  "What would you do if you dropped the cookie jar and it broke?",
  "What would you do if you found a magic wand?",
  "What would you do if you found in the street?",
  "What would you do if you got a present you didn’t like?",
  "What would you do if you got lost in an unfamiliar city?",
  "What would you do if you had four math problems marked wrong that were right?",
  "What would you do if you left something in a locked building?",
  "What would you do if you ordered an ice cream cone and you forgot to bring money?",
  "What would you do if you promised to feed your pet and you didn’t?",
  "What would you do if you saw a friend cheating–report it, confront the friend, nothing–and why?",
  "What would you do if you saw little bugs in your salad?",
  "What would you do if you wanted to be friends with someone who spoke no English?",
  "What would you do if you were at home and your homework was at school?",
  "What would you do if you were in the middle of the lake and your boat began to leak?",
  "What would you do if you were invited to two parties on the same day?",
  "What would you do if you were late for an important appointment?",
  "What would you do if You were the teacher and everyone forgot his homework?",
  "What would you do if you woke up in another country and no one could understand you?",
  "What would you do if your best friend stole something from you?",
  "What would you do if your car got a flat tire on the freeway?",
  "What would you do if your children were caught shoplifting?",
  "What would you do if Your friend had a broken leg? How would you cheer him up?",
  "What would you do if your jelly sandwich fell upside down on the floor?",
  "What would you do if your new shoes felt fine in the store but now they are hurting?",
  "What would you do to entertain your family without spending any money?",
  "What would you invent to make life better?",
  "What would you say if someone told you it was all right to steal from a large department store?",
  "When a friend was in an embarrassing situation, what did you do?",
  "When are you happiest?",
  "When do you feel proud?",
  "When have you felt lonely?",
  "When it might hurt their feelings, how do you feel about telling your friends the truth?",
  "When might it be bad to be honest?",
  "When someone picks on someone else, how do you feel? What do you do?",
  "When was the last time you cried and why?",
  "When you are angry, how do you look?",
  "When you have a problem who do you talk to? Why?",
  "Where do you think we should go on our class fieldtrip this year? Why?",
  "Where would you prefer to be right now–mountains, desert, beach–and why?",
  "Who or what has had a strong influence in your life?",
  "Why do you think adults smoke/drink?",
  "Why do you think prejudice exists in the world?",
  "Why do you think some people encourage others to smoke/drink?",
  "Why do you think some people take advantage of others?",
  "Why do you think tact is an important quality?",
  "Why do you think the rules you must follow are good or bad?",
  "Why have men and women usually only done certain types of work?",
  "Why is exercise important to someone your age?",
  "Why is important to have good manners?",
  "Why is it important to be honest?",
  "Why is it not wise to squander your money?",
  "Why should or shouldn’t a man stay home to care for the house and children while his wife goes to work?",
  "Why would a Prime Minister have a sign on his desk which read, “The buck stops here”?",
  "Why would it be good to be honest?",
  "Why would we say that someone is “passing the buck”?",
  "Would you like to be famous? Why or why not? What would you like to be famous for?",
  "Zoos are sometimes seen as necessary but not poor alternatives to a natural environment.  Discuss some of the arguments for and/or against keeping animals in zoos.",
  "Imaginethat your teacher wants to teach a new subject for the next few weeks.  Your teacher will take suggestions, and then let the students vote on the new subject. What subject should your class choose? Write an essay to support your choice and to persuade the other students to vote for your choice.",
  "Are actors and professional athletes paid too much?",
  "Should teachers have to wear uniforms or have a dress code?",
  "Since the invention of nuclear weapons we have had a long period of GLOBAL peace and stability.  Are nuclear weapons global peacemakers or killing devices?",
  "Should boys and girls be in separate classes?",
  "Is the death penalty effective?",
  "To what extent is the use of animals in scientific research acceptable?",
  "What age is appropriate for dating?",
  "Pretend you woke up one day and there were no rules. People could suddenly do whatever they wanted! Explain what the world would be like. Use your    imagination!",
  "Should student’s textbooks be replaced by notebook computers?",
  "Should students be allowed to have cell phones in elementary and high schools?",
  "Should wealthy nations be required to share their wealth among poorer nations?"
]

const compositions = [
  "Many people believe that television violence has a negative effect on society because it promotes violence. Do you agree or disagree? Use specific reasons and examples to support your response.",
  "According to some people, elderly drivers should be required to reapply for their driving licenses because with age comes diminished vision, hearing, and reaction time. How do you feel about this issue? Explain what you think should be done and why.",
  "Medical researchers, cosmetic companies, and others often perform experiments on animals. Many people feel that experimentation on animals is wrong and should be stopped immediately because animals do feel pain, and there are other alternatives. How do you feel? State your position and explain your reasons.",
  "In order to save money, your principal is thinking about canceling all field trips for the remainder of the year. Write an essay persuading him or her to allow students to continue attending field trips. Use specific reasons and examples to support your response.",
  "Some people are actively involved in promoting and supporting a cause, such as the release of international political prisoners or protecting the environment. Is there a cause you actively support? Write an essay convincing readers to support that cause.",
  "Since the cloning of the sheep Dolly, there has been much debate over whether or not human beings should be cloned. Many people feel this is a violation of the natural order of things and that all research in the area of human cloning should be banned. Others feel that this is a natural progression of science and human evolution and that research in the area of human cloning should be a priority. How do you feel about this issue? Use specific reasons and examples to support your position.",
  "Many parents give children a weekly or monthly allowance regardless of their behavior because they believe an allowance teaches children to be financially responsible. Other parents only give children an allowance as a reward for completing chores or when they have behaved properly. Explain what you think parents should do and why.",
  "Many people volunteer their time to help others, either through non-profit organizations, churches, or other charitable venues. Write an essay convincing readers to find a charity and volunteer their time.",
  "All-girl schools have been gaining popularity in recent years because of the belief that girls learn better when they aren’t competing with or intimidated by boys, who statistically get more attention in the classroom. Do you think single-sex schools are a good idea? Why or why not? Use specific reasons and examples to support your position.",
  "We all have favorite activities that we enjoy. Write an essay convincing readers to try the activity that you enjoy most.",
  "Research shows that the average American watches as much as six hours of television each day. Do you think this is too much? Write an essay convincing readers to spend less time in front of the TV.",
  "Many junior high and high schools around the country now require students to spend a certain number of hours each term doing volunteer work or community service. Some people believe this is an excellent idea that promotes good citizenship and cultivates compassion. Others feel that forced volunteerism is not volunteerism at all. How do you feel about this issue? Use specific reasons and examples to support your position.",
  "Most states allow people to get a driver’s license at the age of 16. Some people feel that 16 is much too young for the responsibility that comes with driving a car and that teenagers should not be allowed to drive until the age of 18. In your opinion, at what age should people be allowed to drive, and why?",
  "As part of the “war on drugs” and in reaction to an increase in school violence, many schools across the nation now conduct targeted searches of student lockers and backpacks. Although the Supreme Court has ruled that public school officials have the right to search students’ persons and property when they have reasonable cause to suspect weapons or drugs, many people feel this is a gross violation of students’ right to privacy. Others feel that since school officials are responsible for the well-being of students while they are in the building, they have the right to search for drugs or weapons at any time. How do you feel about this issue? State your position and explain your reasons with specific examples.",
  "Write an essay convincing readers to break a specific habit that is harmful to their physical, emotional, or financial health.",
  "In many countries, citizens are required to serve in the military for a year or more. Do you believe the United States should institute a similar practice? Why or why not? Use specific reasons and examples to support your answer.",
  "Have you ever traveled to a place that you found very meaningful and rewarding? Write an essay that persuades others to visit this important place.",
  "Many of us spend hours in front of our computers and communicate more by e-mail or instant-messaging than in person. Some people believe that this is good because it helps shy people communicate more openly with others. Others believe that computer communication prevents us from developing interpersonal skills and limits our ability to have meaningful relationships with others. How do you feel about this issue? Use specific reasons and examples to support your position.",
  "Some companies offer a paternity leave that allows fathers to stay home with their newborns for several weeks while still earning partial pay and benefits. Do you think this is a good policy? Why or why not? Explain your answer.",
  "According to some health organizations, many foods on our grocery store shelves are made with genetically modified ingredients. Most of these foods, however, do not have a GMO (genetically modified organism) label. Do you think there should be a law requiring manufacturers to label foods containing GMOs? Use specific reasons and examples to support your position.",
  "More and more farmers and food manufacturers are genetically modifying their crops to reduce susceptibility to disease, improve flavor, and reduce costs. Do you think genetically modifying foods is a good idea? Why or why not? Use specific reasons and examples to support your position.",
  "A few decades ago, many families had half a dozen or more children. Nowadays, more and more families are choosing to have only one or two children. Are smaller families better than larger ones? Why or why not? State your position and support it with specific reasons and examples.",
  "Representatives of credit card companies can often be found on college campuses offering special incentives to get students to fill out credit card applications. Many people feel that this takes advantage of students, who are often low on cash during their college years. Others feel that it is an excellent way to help students begin to build credit and learn financial responsibility. How do you feel about this issue? Take a position and use specific reasons and examples to support your argument.",
  "Good habits improve our physical, emotional, and/or financial health. Select one of your good habits and write an essay persuading readers to make that habit a part of their lives.",
  "What is your all-time favorite movie and why? Write an essay persuading readers to watch this film.",
  "Today, there are more and more reality shows on television. Do these shows make good television? Why or why not? Explain your answer using specific reasons and examples.",
  "Is “an eye for an eye” a good basis for determining an appropriate punishment? Why or why not? Use specific reasons and examples to explain your position.",
  "Many cities suffer from serious air and noise pollution—as well as endless traffic jams—because of too many cars. Some people feel that cities with extensive public transportation systems should ban passenger cars and force people to walk, bike, or use public transportation. Do you think this is a good idea? Why or why not?",
  "On today’s talk shows, guests and audience members often argue heatedly with each other, and on more than one occasion, guests and audience members have been hurt. Do today’s talk shows go too far? Explain your answer.",
  "Have you ever made a change that improved your life or the lives of others? Write an essay that convinces readers to make a change for the better.",
  "The singer and songwriter Bob Dylan once wrote, “A man is a success if he gets up in the morning and gets to bed at night and in between does what he wants to do.” Do you agree with this definition of success? Why or why not? Use specific reasons and examples to support your position.",
  "Carpooling, recycling, and planting trees are all activities that are good for the environment. Write an essay convincing readers to actively participate in one of these activities.",
  "The Internet includes many websites with images and content that are inappropriate. Should websites like these be censored by parents? Why or why not? State your position and support it with specific reasons and examples.",
  "Some people prefer to live in the quiet of the country; others prefer the hustle and bustle of the city. Which do you think is the better choice? State your position and support it with specific reasons and examples.",
  "Is there a book that you feel should be required reading for everyone? Write an essay persuading your audience to read this book.",
  "Some people go right on to college after high school; others take a year or more off to work or travel. Which do you think is the better choice? State your position and support it with specific reasons and examples.",
  "Some people think of the United States as a nation of “couch potatoes.” Write an essay persuading readers to be more physically active.",
  "You have been asked to write a brochure to attract visitors to your hometown. Write an essay that convinces people to visit the place where you live.",
  "Many states have increased the speed limit from 55 miles per hour to 65 miles per hour or more on major turnpikes and thruways. Do you think it is wise to allow motorists to drive over 65 miles per hour? Why or why not? Explain your position using specific reasons and examples.",
  "Nowadays, the private life of a politician is hardly private. In your opinion, should we be so concerned with the private affairs of a politician or political candidate? State your position and support it with specific reasons and examples.",
  "Today’s top professional athletes often have salaries and bonuses in the tens of millions of dollars. Do you think these athletes deserve such high compensation? Why or why not? Explain your position and use specific reasons and examples.",
  "Many parents do not allow their children to play with toy guns. In your opinion, is this a wise decision? Explain what you think parents should do about toy guns and why.",
  "For centuries, people have wondered about the possibility of life on other planets in the universe. Do you believe extraterrestrial life exists? Write an essay persuading others to share your point of view.",
  "Many science fiction stories deal with the possibility of being able to “design” our children by choosing the specific physical and personality traits we would like them to have. Do you think this is a good idea? Why or why not? Use specific reasons and examples to support your position.",
  "If someone discovered a formula that would enable us to live forever, would that be a blessing or a curse? Use specific reasons and examples to support your answer.",
  "Some educators argue that every child in every school should have access to computers. Others believe that the value of computers in the classroom is overrated and that computers may actually interfere with the learning process. In your opinion, how important are computers in the classroom? Use specific reasons and examples to explain your answer.",
  "Should the United States invest more time, money, and effort in space exploration? Why or why not? Use specific reasons and examples to explain your position.",
  "Some people believe that students aren’t learning enough in high school. Should school standards be higher? Explain your answer using specific reasons and examples.",
  "It has often been said, “Ignorance is bliss,” and “What you don’t know won’t hurt you.” Do you agree with these statements? Why or why not?",
  "Although foreign aid spending is typically only a very small portion of our annual budget (currently about .1% of the Gross National Product), the United States still spends billions of dollars a year on foreign aid. Some people feel this is too much and that we should spend nearly all of our money addressing problems here at home. Others feel it is not nearly enough and that we should spend a great deal more helping other nations. How do you feel about this issue? Explain what you think we should do and why.",
  "Some people fish to eat what they catch; others fish simply for the “sport,” returning the fish to the water after they’ve caught it. Many animal rights activists argue that sport fishing is cruel and should be abolished. How do you feel about this issue? State your position and support it with specific reasons and examples.",
  "Many schools employ security guards and have installed security equipment such as video cameras and metal detectors in the building. In your opinion, how should security in public schools be handled? Use specific reasons and examples to support your answer.",
  "Across the country, public places such as libraries and museums are now smoke-free environments, and restaurants are required to have separate smoking and non-smoking sections. Some smoke- free advocates are now campaigning to ban smoking in all restaurants and bars. Do you think this is a good idea? Why or why not? Use specific reasons and examples to support your position.",
  "In a small minority of schools across the nation, students do not earn grades; rather, they receive regular written and oral evaluations of their work. Some people believe that this is more effective for learning than the grading system, which they believe rewards students unevenly and encourages a competitiveness that is counterproductive to learning. How do you feel about this issue? Use specific reasons and examples to support your answer.",
  "Is reading fiction a waste of time? Why or why not? Explain your answer using specific reasons and examples to support your position.",
  "Many schools offer students who are native speakers of another language the opportunity to take classes in their native tongue so that they can more easily assimilate and better understand the material. Some educators believe that this is a disservice and that these students should be immersed in the English language. How do you feel about this issue? Use specific reasons and examples to support your position.",
  "Many people immigrate to the United States because they believe that it is better than their native country. In fact, many people believe that the United States is the best country in the world. Do you agree? Why or why not?",
  "Some people think that school cafeterias should be required to provide low-fat and/or vegetarian lunch options to accommodate the eating habits of all students. Do you agree or disagree? Explain your position and use specific reasons and examples as support.",
  "Elementary and secondary schools around the country are beginning to actively address the problem of bullies. In your opinion, is bullying an issue that should be addressed by schools or left to parents? Use specific reasons and examples to support your position.",
  "Most private schools require students to wear uniforms. Should public school students wear uniforms too? Argue for or against school uniforms for public school students. Use specific reasons and examples to support your position.",
  "Do you think that the movie and/or TV ratings systems are effective or useful? Use specific reasons and examples to support your position.",
  "Many people believe that honesty is the best policy. In your opinion, is it ever okay to lie? Explain your answer using specific reasons and examples.",
  "In order to solve your school’s recent litter problem, your principal asked students to take better care of the campus, but the litter problem continued. Your principal’s reaction is to cancel all extracurricular activities until the problem is resolved. Do you agree or disagree with his reaction? Use specific reasons and examples to support your position.",
  "If an alumnus donated a large sum of money to your school, how do you think that money should be spent? Write an essay convincing school officials to allocate the money in the way you think is best for the school.",
  "Many people feel that American society is too competitive. Do you agree? If so, is this a good thing or a bad thing? Use specific reasons and examples to support your answer.",
  "If it were up to you to choose one item from the twenty-first century to place in a time capsule for future generations, what would you choose? Use specific reasons and examples to support your choice, explaining both the item’s significance and the reasons why it embodies the culture of the early twenty-first century.",
  "Who makes a better leader: someone who is loved, or someone who is feared? Take a position and explain your answer.",
  "Some people are concerned that many teachers are not sufficiently qualified for the classroom and argue that they should be required to pass competency tests before they are allowed to teach. Do you agree? Why or why not? Explain your answer with specific reasons and examples.",
  "If it were up to you to choose one professional (a doctor, a reporter, a scientist, a politician, an actor) to travel aboard the next space station, who would you choose and why? Use specific reasons and examples to support your choice.",
  "In our increasingly global society, many people feel that all students should be required to learn a foreign language before graduating from high school. Do you agree? Why or why not? Explain your position using specific reasons and examples.",
  "Today, more and more colleges and universities are offering not only individual courses but entire degree programs online. Some educators worry that online programs do not provide the same quality as an on-campus education and that in an online program, students can get others to do their work. Others believe online courses offer convenience and flexibility enabling students, who might otherwise not be able, to earn a degree and complete their educations. In your opinion, should colleges and universities offer degrees entirely online? Why or why not?",
  "Is a good education a right or a privilege? Why do you think so? Use specific reasons and examples to explain your answer.",
  "The network that runs your favorite television show has suddenly decided to cancel it. Write a letter convincing the station to continue running the show.",
  "What would improve your hometown? Write an essay convincing town officials to make a change that would improve your neighborhood.",
  "Many people complain that American news shows focus too much on sensational items, such as local crimes and celebrity gossip, and spend too little time on important national and international news. In your opinion, should television news devote more time and coverage to international news and global issues? Why or why not?",
  "Most students enjoy the long stretch of summer vacation, but some parents and educators feel that two and a half months is too long a break from school. Some argue that students and families would be better served if the school year were extended through July, with a three or four-week break in August, a longer winter break, and a week off each in the spring and fall. Does this sound like a good idea to you? Why or why not? Explain your answer.",
  "Many people feel that the use of surveillance cameras in public places, such as parking lots, is a good idea that can help ensure our safety. Others worry that too many cameras violate our right to privacy and give law enforcement officials too much power. In your opinion, should we install more surveillance cameras in public places? Why or why not? Support your position with specific reasons and examples.",
  "It has often been said, “a little knowledge is a dangerous thing.” Do you agree? Why or why not? Use specific reasons and examples to explain your answer.",
  "Recent studies have shown that students often perform better on exams if classical music is played softly in the background. However, some students may find the music distracting. Should schools play classical music during exams and/or allow students to listen to it on headphones? Take a position and explain your answer.",
  "All across the country, state laws require drivers to wear seatbelts. Not everyone believes the use of seatbelts should be mandatory. What do you think? Make a case for or against mandatory seatbelt use. Use specific reasons and examples to support your position.",
  "Most schools require students to read “old” texts such as ancient Greek tragedies or Shakespearian plays. Many students wonder why they should read these texts instead of more contemporary material. Make a case for or against the reading of classical literature in English classes.",
  "Should a parent be a child’s disciplinarian, or a child’s best friend? Take a position and explain your answer using specific reasons and examples.",
  "More and more Americans are deciding to eliminate meat from their diets and become vegetarians. Do you think this is a good idea? Argue for or against becoming a vegetarian. Use specific reasons and examples to support your position.",
  "With the current popularity of sport utility vehicles many people believe that it’s more important than ever for Congress to pass legislation requiring automobile manufacturers to use more fuel- efficient engines. Do you agree that such a law should be passed? Why or why not? Use specific reasons and examples to support your argument.",
  "Every year, millions of people visit zoos around the world. But some people believe that zoos are inhumane and that animals should not be kept in captivity. Do you agree? Why or why not? Use specific reasons and examples to support your position.",
  "Politicians come from all sorts of professional backgrounds, from lawyers and chief executive officers to actors and even professional wrestlers. On a few notable occasions, politicians with criminal backgrounds have even been elected. In your opinion, should candidates with a criminal record be allowed to run for office? Why or why not? Use specific reasons and examples to support your answer.",
  "Students who don’t want to do their homework can find dozens of sites on the Internet that offer essays for sale. Do you think this is a legitimate business, or should these enterprises be shut down? Use specific reasons and examples to support your answer.",
  "Do you think the SAT or ACT exam is an accurate measure of a student’s aptitude for college? Support your position with specific examples.",
  "It has often been said that we can lie with silence as well as with words. Do you agree? Why or why not? Explain your answer.",
  "Many students complain about having to learn history. Why do we need knowledge of the past? Write an essay convincing skeptics that learning about the past is important.",
  "Woodrow Wilson once said, “Friendship is the only cement that will hold the world together.” Do you agree? Use specific reasons and examples to explain your answer.",
  "Charles Simmons said, “Live only for today, and you ruin tomorrow.” Do you agree? Why or why not? Explain your answer.",
  "Thomas Edison, the renowned inventor, is famous for having said, “Genius is one percent inspiration, ninety-nine percent perspiration.” Do you agree with this definition of genius? Why or why not?",
  "Many of us are fond of music that speaks to our particular generation. Write an essay that convinces others not in your generation that your music is worth listening to.",
  "Alexander Smith said, “The great man is the man who does a thing for the first time.” Do you agree with this definition of greatness? Why or why not?",
  "The eighteenth century writer Samuel Johnson wrote, “Ignorance, when voluntary, is criminal.” Do you agree? Use specific reasons and examples to explain your answer.",
  "For decades, elementary school children across the country had been required to stand and say the Pledge of Allegiance to the American flag every school-day morning. That practice has recently been called into question, and standing and reciting the pledge is now voluntary. In your opinion, should students be required to say the pledge, should it remain voluntary, or should the practice be completely abandoned? State your position and use specific reasons and examples to support it.",
  "Currently, Americans pay taxes based upon how much they earn: the higher their income, the higher the percentage of that income they must pay in taxes. Many people have been arguing that a flat tax, in which everyone pays the same rate regardless of income, would be a more equitable and desirable tax system. Which of these two tax systems do you think is best, and why? Use specific reasons and examples to support your answer.",
  "The great inventor Charles F. Kettering said, “The price of progress is trouble.” Do you agree with Kettering’s assessment of progress? Why or why not? Use specific reasons and examples to support your answer.",
  "The writer Thomas Mann said, “War is only a cowardly escape from the problems of peace.” Do you agree with this claim? Why or why not? Use specific reasons and examples to support your answer.",
  "Activist Jeannette Rankin once said, “You can no more win a war than you can win an earthquake.” Do you agree with this statement? Why or why not? Use specific reasons and examples to support your answer.",
  "Write an essay explaining why you should be admitted to a particular college.",
  "The Roman leader Seneca said, “A great fortune is a great slavery.” Do you agree with this claim? Why or why not? Use specific reasons and examples to support your answer.",
  "If your readers were to learn a foreign language, which language do you think they should learn, and why? Write an essay convincing readers to learn that particular language.",
  "Many albums and CDs now contain stickers warning parents that the lyrics of some of the songs may not be suitable for children. Some people argue that simply putting a sticker on a label is not enough. What do you think the record industry should do to warn parents about inappropriate lyrics? Explain what you think should be done and why.",
  "Should we devote time and money to building a space station on the moon or Mars? Why or why not? Explain your answer.",
  "Should people lease or buy new cars? Make a case for the option that you think is best. Use specific reasons and examples to support your position.",
  "The inventor and statesman Benjamin Franklin said, “Money never made a man happy yet, nor will it. There is nothing in its nature to produce happiness.” Do you agree with this statement? Why or why not? Use specific reasons and examples to support your position.",
  "Some states have now made it illegal to drive while talking on a hand-held cellular phone. Do you think this is a good law that should be passed in other states as well? Why or why not? Explain your answer.",
  "The poet W. H. Auden wrote, “Machines are beneficial to the degree that they eliminate the need for labor, harmful to the degree that they eliminate the need for skill.” Do you agree? Why or why not? Use specific reasons and examples to explain your answer.",
  "Are students learning enough science in high school? Argue for or against an expanded science requirement in secondary schools.",
  "According to an old Greek proverb, “All things good to know are difficult to learn.” Do you agree? Why or why not? Use specific reasons and examples to explain your answer.",
  "William Hazlitt wrote, “Man is a make-believe animal—he is never so truly himself as when he is acting a part.” Do you agree? Explain your answer using specific reasons and examples.",
  "Imagine that you have a relative who is unfamiliar with computers and has never been on the Internet. Write an essay convincing this relative to get a computer and get online.",
  "Imagine that you have found a great apartment to share, but your new roommate doesn’t want any pets. Write an essay persuading your roommate to let you bring your pet with you.",
  "According to a Czechoslovakian proverb, “Better a lie that soothes than a truth that hurts.” Do you agree? Why or why not? Use specific reasons and examples to explain your answer.",
  "Imagine that your high school (or alma mater) has decided to do away with a club to which you belong (or used to belong). Write an essay persuading school officials not to disband that organization.",
  "“Original” fairy tales, like those recorded by the Brothers Grimm, often contain violence. Some literary critics and child psychologists believe these tales are good for children because they address children’s real fears, feelings, and desires. Others argue that contemporary “sanitized” fairy tales still convey the main themes of the tales and are far more appropriate for children. How do you feel about this issue? Use specific reasons and examples to explain your answer.",
  "Imagine that you have made it to the final round of interviews for a new job. Convince your prospective employers that you are the one who most deserves the position.",
  "Most high school schedules include a study hall period several times a week. Is study hall a waste of time, or a necessary break from class? State your position and use specific reasons and examples to support your position.",
  "Imagine that you have a friend who doesn’t have any money in his or her savings account. Convince this friend that it’s important to create and follow through with a savings plan.",
  "During the Christmas holiday season, images of Santa Claus are everywhere, and young children often line up to take pictures with adults dressed as Santa. Some people feel that children should not be led to believe that Santa Claus is real. Do you agree? Why or why not? Use specific reasons and examples to support your position.",
  "Is there something that you believe is truly worth fighting for? Write an essay persuading others that this cause is worth a fight.",
  "Write an essay convincing your best friend to try your favorite brand of junk food. Imagine that you have been asked to help raise money for a local charity. Choose a charity and write an essay convincing readers to contribute to the fundraising campaign.",
  "Write an essay about the best movie that you have watched in your life!"
]

function getRandomIntInclusive(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const indexTheam = getRandomIntInclusive(0,themes.length)

console.log(themes[indexTheam])
